name: OPERA-Standardizer-workfow
on: [push, pull_request]

jobs:
  build:
    runs-on: [Skolmar]
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build -t pf_opera_standardizer .
      - uses: actions/checkout@v2
      - name: docker run
        run: |
          docker run --name pf_opera_standardizer_cont -d -it -p 5015:5000 pf_opera_standardizer
      - uses: actions/checkout@v2
      - name: docker exec
        run: |
          docker exec pf_opera_standardizer_cont flask run -h 0.0.0.0 -p 5000
